apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: 2019-03-04T15:38:49Z
  generation: 1
  name: opssights.synopsys.com
  resourceVersion: "18327782"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/opssights.synopsys.com
  uid: 9afd0b26-3e93-11e9-96b1-1206ef5b0bb2
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    description: |-
      CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

      Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    name: Age
    type: date
  group: synopsys.com
  names:
    kind: OpsSight
    listKind: OpsSightList
    plural: opssights
    singular: opssight
  scope: Cluster
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: OpsSight
    listKind: OpsSightList
    plural: opssights
    singular: opssight
  conditions:
  - lastTransitionTime: 2019-03-04T15:38:49Z
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1
